### ISSUE TITLE
Ignore files by username

### ISSUE THREAD

**Issue by papuass** [pixelhaufen/Wiki-Loves-Jurytool#1]
Hello!
It is not uncommon on smaller communities that organizers themselves upload files to contest. They do not compete for the prizes, so their pictures should not be rated. Of course, we can add a new category to exclude them, but "blacklist" of usernames would be more straightforward.

**Comment by martinkraft** [comment]
This tool already takes care that nobody is allowed to vote on his on pictures.
Therefore I don't see any reason, why the the wikipedians, who organise WLM, should be blacklisted in total?!

**Comment by papuass** [comment]
My case is such: We are 2 organizers, the other one took 562 pictures. Our contest rules state that we can not enter to win prizes. So it is pointless for me to judge this amount of pictures.

**Comment by pixelhaufen** [comment]
As a quick fix (untested) you could add the following lines after https://github.com/pixelhaufen/Wiki-Loves-Jurytool/blob/master/lib/commons/list_exclude.php#L101
(Replace username1 and username2 with your organizers.)

```
$sql = "UPDATE `" . $config['dbprefix'] . "fotos` SET exclude='1' WHERE `user` = 'username1'";
$db->query($sql);
$sql = "UPDATE `" . $config['dbprefix'] . "fotos` SET exclude='1' WHERE `user` = 'username2'";
$db->query($sql);
```

**Comment by papuass** [comment]
Thanks, it seems that it has worked.
Appreciate your support!
